config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
  devise_for :users
  resources :categories
  resources :contexts do
    resources :information_posts
    resources :pictures
    resource :favourite, only: %w(update destroy), module: 'contexts'
    resource :redaction, only: %w(edit), module: 'contexts', controller: 'redaction'
    collection do
      get 'redaction', controller: 'contexts/redaction', action: 'index'
    end
  end
  resources :webscraping, only: %w(index), module: 'contexts'
  root 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/context.rb
class Context < ApplicationRecord
  belongs_to :user
  belongs_to :category
  has_many :information_posts, dependent: :destroy
  has_many :favourites
  #has_many :favourited_by, through: :favourites,  class_name: "User", foreign_key: "user_id"
  validates :category_id,  presence: true
  validates :title,  presence: true,
                     length: { minimum: 5 }
  has_many :pictures, dependent: :destroy
  enum status: { draft: 0, published: 1 }

  def favourited?(user)
    user.favourite_for self
  end

  def favourite!(user)
    favourite = user.favourites.build(context_id: self.id)
    favourite.save!
  end

  def unfavourite!(user)
    unfavourite = user.favourite_for(self)
    unfavourite.destroy!
  end


end

app/controllers/contexts/favourites_controller.rb
class Contexts::FavouritesController < ApplicationController
  before_action :load_context, :authenticate_user!

  def update
    @context.favourite!(current_user)
  end

  def destroy
    @context.unfavourite!(current_user)
  end

  private

  def load_context
    @context = Context.find(params[:context_id])
  end

end

app/controllers/contexts/redaction_controller.rb
class Contexts::RedactionController < ApplicationController
  before_action :set_context, only: [:edit]
  before_action :authenticate_context_owner!, only: [:edit]

  def index
    @contexts = current_user.contexts
  end

  def edit
  end

  private
  def set_context
    @context = Context.find(params[:context_id])
  end
  def authenticate_context_owner!
    if @context.user_id != current_user.id
      redirect_to "/", notice: 'You are not authorized to do this action'
    end
  end
end

app/controllers/contexts/webscraping_controller.rb
class Contexts::WebscrapingController < ApplicationController
  def index
    url = params[:url]

    mechanize = Mechanize.new
    page = mechanize.get(url)
    title = ''
    page.search('h1').each do |h1|
      title = h1.text.strip
    end
    @title = title

    summary = get_from_twitter_tags(page)
    summary = get_from_property_twitter_tags(page) if summary.nil?
    summary = get_from_property_facebook_tags(page) if summary.nil?

    @summary = summary.nil? ? 'unknown': summary[:content]

  end

  private

  def get_from_twitter_tags(page)
    page.at('meta[name="twitter:description"]')
  end

  def get_from_property_twitter_tags(page)
    page.at('meta[property="twitter:description"]')
  end

  def get_from_property_facebook_tags(page)
    page.at('meta[property="og:description"]')
  end

end

app/controllers/contexts_controller.rb
class ContextsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]

  def index
    @contexts = Context.published
  end

  def show
    @context = Context.find(params[:id])
    if @context.draft? && (@context.user_id == current_user.id)
      redirect_to edit_context_redaction_path(@context)
    elsif @context.draft? && (@context.user_id != current_user.id)
      redirect_to contexts_path, alert: 'You are not authorized for this action'
    end
  end

  def new
    @context = Context.new
    @submit = "New context"
  end

  def edit
    @context = Context.find(params[:id])
    @submit = "Edit context"
  end

  def create
    @context = current_user.contexts.new(context_params) rescue nil

    if @context && @context.save
      redirect_to @context, notice: 'Context saved!'
    else
      flash[:alert] = 'Something went wrong'
      render 'new'
    end
  end

  def update
    @context = Context.find(params[:id])
    if @context.update!(context_params)
      redirect_to @context
    else
      render 'edit'
    end
  end

  def destroy
    @context = Context.find(params[:id])
    if @context.user_id == current_user.id
      @context.destroy
      redirect_to contexts_path, notice: 'Context deleted!'
    else
      redirect_to contexts_path,  alert: 'You are not authorized for this action'
    end
  end


  private
  def context_params
    params.require(:context).permit(:title, :description, :category_id, :status)
  end
end

app/controllers/redaction_controller.rb
class RedactionController < ApplicationController
  before_action :authenticate_context_owner!

  def edit
  end

  def update
  end

  private
  def authenticate_context_owner!
    @context = Context.find(params[:id])
    if @context.user_id != current_user.id
      redirect_to "/", notice: 'You are not authorized to do this action'
    end
  end
end

app/helpers/contexts_helper.rb
module ContextsHelper

  def link_to_toggle_context_favourite(context, user)
    url = context_favourite_path(context)

    if context.favourited?(user)
      link_to_with_icon('fa fa-heart', url, {
        method: 'DELETE',
        remote: true,
        class: 'favourite favourite-heart',
      })
    else
      link_to_with_icon('fa fa-heart-o', url, {
        method: 'PUT',
        remote: true,
        class: 'favourite unfavourite-heart',
      })
    end
  end

  def link_to_with_icon(icon_css, url, options = {})
    icon = content_tag(:i, nil, class: icon_css)
    link_to(icon.html_safe, url, options)
  end

  def load_image_for(context)
    if context.pictures.any?
      image_tag context.pictures.sample.image, class: "img-fluid"
    else
      image_tag "info-context.jpg", class: "img-fluid"
    end
  end
end

app/views/contexts/redaction/edit.html.erb
<div class="container mt-4 mb-4 bg-light" >
  <%= link_to 'Back', contexts_path %>
  <div class="row justify-content-around">
    <div class="col-sm-6 col-md-8">
      <h1><%= @context.title %></h1>
      <p><strong>Author:</strong><%= @context.user.email %></p>
      <p><strong>Description:</strong><%= @context.description %></p>
      <% if current_user && @context.user_id == current_user.id %>
        <%= link_to 'Edit', edit_context_path(@context), class: "btn btn-outline-primary btn-sm mb-3" %>
      <% end %>
      <% if @context.draft? %>
        <%= link_to 'Publish', context_path(@context, { context: {status: 'published'} }), method: :put, class: "btn btn-outline-primary btn-sm mb-3" %>
      <% else %>
        <%= link_to 'Unpublish', context_path(@context, { context: {status: 'draft'} }), method: :put, class: "btn btn-outline-primary btn-sm mb-3" %>
      <% end %>
    </div>
    <div class="col-sm-6 col-md-4">
      <div class="row justify-content-center mb-2">
        <%= link_to 'Add Image', new_context_picture_path(@context), class: "btn  btn-outline-primary btn-sm " %>
      </div>
      <div class="row justify-content-center mb-1">
        <%if @context.pictures.empty?%>
          <img class="img-fluid mx-auto" data-src="holder.js/150x150/auto" alt="Generic placeholder image">
        <%else%>
          <% @context.pictures.each do |picture| %>
            <%= image_tag(picture.image, class: "img-fluid mx-auto image-context") %>
          <%end%>
        <%end%>
      </div>
    </div>
  </div>
</div>

<div class="container">
  <div class="row">
    <div class="col-sm-12">
      <div class="card-header">
        <h3 class="card-title">Information <%= link_to 'Add information', new_context_information_post_path(@context), class: "btn btn-primary btn-sm" %></h3>
      </div>
      <div class="card-body">
        <% @context.information_posts.each do |information_post| %>
          <h5 class="card-title"><%= information_post.title %></h5>
          <p class="card-text"><%= information_post.summary %></p>
          <a href="<%= information_post.url %>"><%= information_post.url %></a>
          <p class="mt-3">
            <% if current_user && @context.user_id == current_user.id %>
              <%= link_to 'Edit', edit_context_information_post_path(@context, information_post), class: "btn btn-outline-primary btn-sm" %>
              <%= link_to 'Destroy Information', context_information_post_path(@context, information_post), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-outline-danger btn-sm" %>
            <% end %>
         </p>
         <hr>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/contexts/redaction/index.html.erb
<div class="container">
<table class="table">
  <thead class="thead-dark">
    <tr>
      <th scope="col">#</th>
      <th scope="col">Title</th>
      <th scope="col">Description</th>
      <th scope="col">Status</th>
      <th scope="col">Actions</th>
    </tr>
  </thead>
  <tbody>
  <% @contexts.each_with_index do |context, index| %>
    <tr>
      <th scope="row"><%= index + 1 %></th>
      <td><%= context.title %></td>
      <td><%= context.description %></td>
      <td><%= context.status %></td>
      <td><%= link_to 'Redact', edit_context_redaction_path(context), class: "btn btn-outline-primary btn-sm mb-3" %></td>
    </tr>
  <% end %>
  </tbody>
</table>
</div>