config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
  devise_for :users
  resources :categories
  resources :contexts do
    resources :information_posts
    resources :pictures
    resource :favourite, only: %w(update destroy), module: 'contexts'
    resource :redaction, only: %w(edit), module: 'contexts', controller: 'redaction'
    collection do
      get 'redaction', controller: 'contexts/redaction', action: 'index'
    end
  end
  resources :webscraping, only: %w(index), module: 'contexts'
  root 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/shared/_accordian.html.erb
<div class="accordian py-3" id="accordianExample">
  <% @context.information_posts.each_with_index do |information_post, index| %>
  <div class="card">
    <div class="card-header" id="headingOne-<%= information_post.id %>">
      <h3 class="mb-0">
        <button class="btn btn-link" type="button" data-toggle="collapse" data-target="#collapseOne-<%= information_post.id %>" aria-expanded="true" aria-controls="collapseOne">
          <%= information_post.title %>
        </button>
      </h3>
    </div>

    <div id="collapseOne-<%= information_post.id %>" class="collapse <%= index.zero? ? 'show' : '' %>" aria-labelledby="headingOne" data-parent="#accordianExample">
      <div class="card-body">
        <%= information_post.summary %>
        <p class="mt-3">
        <a href="<%= information_post.url %>"><%= information_post.url %></a>
      </p>
        <p class="mt-3">
          <% if current_user && @context.user_id == current_user.id %>
            <%= link_to 'Edit', edit_context_information_post_path(@context, information_post), class: "btn btn-outline-primary btn-sm" %>
            <%= link_to 'Destroy Information', context_information_post_path(@context, information_post), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-outline-danger btn-sm" %>
          <% end %>
       </p>
      </div>
    </div>
  </div> <!-- end card one -->
  <% end %>
</div> <!-- end accordian -->

app/views/shared/_footer.html.erb
<!-- Start footer -->
<footer id="mu-footer">
  <div class="mu-footer-top">
    <div class="container">
      <div class="row">
        <div class="col-md-3">
          <div class="mu-single-footer">
            
            <p>CONTEXTO</p>
            <div class="mu-social-media">
              <a href="https://github.com/gaspachoio"><i class="fa fa-github"></i></a>
              <a class="mu-twitter" href="https://twitter.com/GaspachoDev"><i class="fa fa-twitter"></i></a>
              <a class="mu-google-plus" href="#"><i class="fa fa-google-plus"></i></a>
              <a class="mu-youtube" href="#"><i class="fa fa-youtube"></i></a>
            </div>
          </div>
        </div>
        <div class="col-md-3">
          <div class="mu-single-footer">
            <h3>Twitter feed</h3>
            <ul class="list-unstyled">
                <li class="media">
                 <span class="fa fa-twitter"></span>
                  <div class="media-body">
                    <p><strong>@b_hero</strong> Lorem ipsum dolor sit amet, consectetuer adipiscing elit.</p>
                    <a href="#">2 hours ago</a>
                  </div>
                </li>
                <li class="media">
                  <span class="fa fa-twitter"></span>
                  <div class="media-body">
                    <p><strong>@b_hero</strong> Lorem ipsum dolor sit amet, consectetuer adipiscing elit.</p>
                    <a href="#">2 hours ago</a>
                  </div>
                </li>
            </ul>
          </div>
        </div>
        <div class="col-md-3">
          <div class="mu-single-footer">
            <h3>Useful link</h3>
            <ul class="mu-useful-links">
              <li><a href="https://github.com/mers85/contextos">Context repository</a></li>
              <li><a href="#">What is a context?</a></li>
              <li><a href="#">How to create a context?</a></li>
            </ul>
          </div>
        </div>
        <div class="col-md-3">
          <div class="mu-single-footer">
            <h3>Contact Information</h3>
            <ul class="list-unstyled">
              <li class="media">
                <span class="fa fa-home"></span>
                <div class="media-body">
                  <p>349 Main St, Deseronto, ON K0K 1X0, Canada</p>
                </div>
              </li>
              <li class="media">
                <span class="fa fa-phone"></span>
                <div class="media-body">
                   <p>+00 123 456 789 00</p>
                  <p>+ 00 254 632 548 00</p>
                </div>
              </li>
              <li class="media">
                <span class="fa fa-envelope"></span>
                <div class="media-body">
                 <p>support@bhero.com</p>
                 <p>help.behero@gmail.com</p>
                </div>
              </li>
            </ul>
          </div>
        </div>
      </div>
    </div>
    <div class="mu-footer-bottom">
      <div class="container">
        <div class="row">
          <div class="col-md-12">
            <div class="mu-footer-bottom-area">
              <p><a href="https://github.com/gaspachoio">Gaspacho Software</a> &middot; <a href="#">Terms</a></p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>


</footer>
<!-- End footer -->

app/views/shared/_header.html.erb
<!--START SCROLL TOP BUTTON -->
 <a class="scrollToTop" href="#">
	 <i class="fa fa-angle-up"></i>
 </a>
<!-- END SCROLL TOP BUTTON -->
	<header id="mu-hero">
		<div class="container">
			<nav class="navbar navbar-expand-lg navbar-light mu-navbar">
				<!-- Text based logo -->
				<a class="navbar-brand mu-logo" href="/"><span>contexto</span></a>
				<!-- image based logo -->
			   	<!-- <a class="navbar-brand mu-logo" href="index.html"><img src="assets/images/logo.png" alt="logo"></a> -->
			  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
			    <span class="fa fa-bars"></span>
			  </button>

			  <div class="collapse navbar-collapse" id="navbarSupportedContent">
			    <ul class="navbar-nav mr-auto mu-navbar-nav">
			      <li class="nav-item ">
			        <a href="/contexts">Contextos</a>
			      </li>
			       <li class="nav-item dropdown">
				        <a class="dropdown-toggle" href="blog.html" role="button" id="navbarDropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Categories</a>
				       <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                 <% @categories.each do |category| %>
                   <%= link_to category.name, category_path(category.id), class: "dropdown-item" %>
                 <% end %>
				        </div>
				      </li>
              <li class="nav-item dropdown">
 				        <a class="dropdown-toggle" href="blog.html" role="button" id="navbarDropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Account</a>
 				       <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                 <% if user_signed_in? %>
                   <%= link_to "Logged as: " + current_user.email, edit_user_registration_path, class: "dropdown-item" %>
                   <%= link_to "My Contexts", redaction_contexts_path(@context), class: "dropdown-item" %>
                   <%= link_to "Logout", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
                 <% else %>
                   <%= link_to "Sign Up", new_user_registration_path, class: "dropdown-item" %>
                   <%= link_to "Login", new_user_session_path, class: "dropdown-item" %></a>
                 <% end %>
 				       </div>
 				      </li>
			    </ul>
			  </div>
			</nav>
		</div>
	</header>
	<!-- End Header -->