config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
  devise_for :users
  resources :categories
  resources :contexts do
    resources :information_posts
    resources :pictures
    resource :favourite, only: %w(update destroy), module: 'contexts'
    resource :redaction, only: %w(edit), module: 'contexts', controller: 'redaction'
    collection do
      get 'redaction', controller: 'contexts/redaction', action: 'index'
    end
  end
  resources :webscraping, only: %w(index), module: 'contexts'
  root 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/context.rb
class Context < ApplicationRecord
  belongs_to :user
  belongs_to :category
  has_many :information_posts, dependent: :destroy
  has_many :favourites
  #has_many :favourited_by, through: :favourites,  class_name: "User", foreign_key: "user_id"
  validates :category_id,  presence: true
  validates :title,  presence: true,
                     length: { minimum: 5 }
  has_many :pictures, dependent: :destroy
  enum status: { draft: 0, published: 1 }

  def favourited?(user)
    user.favourite_for self
  end

  def favourite!(user)
    favourite = user.favourites.build(context_id: self.id)
    favourite.save!
  end

  def unfavourite!(user)
    unfavourite = user.favourite_for(self)
    unfavourite.destroy!
  end


end

app/controllers/contexts/favourites_controller.rb
class Contexts::FavouritesController < ApplicationController
  before_action :load_context, :authenticate_user!

  def update
    @context.favourite!(current_user)
  end

  def destroy
    @context.unfavourite!(current_user)
  end

  private

  def load_context
    @context = Context.find(params[:context_id])
  end

end

app/controllers/contexts/redaction_controller.rb
class Contexts::RedactionController < ApplicationController
  before_action :set_context, only: [:edit]
  before_action :authenticate_context_owner!, only: [:edit]

  def index
    @contexts = current_user.contexts
  end

  def edit
  end

  private
  def set_context
    @context = Context.find(params[:context_id])
  end
  def authenticate_context_owner!
    if @context.user_id != current_user.id
      redirect_to "/", notice: 'You are not authorized to do this action'
    end
  end
end

app/controllers/contexts/webscraping_controller.rb
class Contexts::WebscrapingController < ApplicationController
  def index
    url = params[:url]

    mechanize = Mechanize.new
    page = mechanize.get(url)
    title = ''
    page.search('h1').each do |h1|
      title = h1.text.strip
    end
    @title = title

    summary = get_from_twitter_tags(page)
    summary = get_from_property_twitter_tags(page) if summary.nil?
    summary = get_from_property_facebook_tags(page) if summary.nil?

    @summary = summary.nil? ? 'unknown': summary[:content]

  end

  private

  def get_from_twitter_tags(page)
    page.at('meta[name="twitter:description"]')
  end

  def get_from_property_twitter_tags(page)
    page.at('meta[property="twitter:description"]')
  end

  def get_from_property_facebook_tags(page)
    page.at('meta[property="og:description"]')
  end

end

app/controllers/contexts_controller.rb
class ContextsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]

  def index
    @contexts = Context.published
  end

  def show
    @context = Context.find(params[:id])
    if @context.draft? && (@context.user_id == current_user.id)
      redirect_to edit_context_redaction_path(@context)
    elsif @context.draft? && (@context.user_id != current_user.id)
      redirect_to contexts_path, alert: 'You are not authorized for this action'
    end
  end

  def new
    @context = Context.new
    @submit = "New context"
  end

  def edit
    @context = Context.find(params[:id])
    @submit = "Edit context"
  end

  def create
    @context = current_user.contexts.new(context_params) rescue nil

    if @context && @context.save
      redirect_to @context, notice: 'Context saved!'
    else
      flash[:alert] = 'Something went wrong'
      render 'new'
    end
  end

  def update
    @context = Context.find(params[:id])
    if @context.update!(context_params)
      redirect_to @context
    else
      render 'edit'
    end
  end

  def destroy
    @context = Context.find(params[:id])
    if @context.user_id == current_user.id
      @context.destroy
      redirect_to contexts_path, notice: 'Context deleted!'
    else
      redirect_to contexts_path,  alert: 'You are not authorized for this action'
    end
  end


  private
  def context_params
    params.require(:context).permit(:title, :description, :category_id, :status)
  end
end

app/helpers/contexts_helper.rb
module ContextsHelper

  def link_to_toggle_context_favourite(context, user)
    url = context_favourite_path(context)

    if context.favourited?(user)
      link_to_with_icon('fa fa-heart', url, {
        method: 'DELETE',
        remote: true,
        class: 'favourite favourite-heart',
      })
    else
      link_to_with_icon('fa fa-heart-o', url, {
        method: 'PUT',
        remote: true,
        class: 'favourite unfavourite-heart',
      })
    end
  end

  def link_to_with_icon(icon_css, url, options = {})
    icon = content_tag(:i, nil, class: icon_css)
    link_to(icon.html_safe, url, options)
  end

  def load_image_for(context)
    if context.pictures.any?
      image_tag context.pictures.sample.image, class: "img-fluid"
    else
      image_tag "info-context.jpg", class: "img-fluid"
    end
  end
end

app/views/contexts/_context_card.html.erb
<div class="col-md-4 mt-3">
  <article class="mu-blog-item">
    <div class="context-img">
      <a href="<%=context_path(context)%>"><%= load_image_for(context) %></a>
    </div>
    <div class="mu-blog-item-content">
      <ul class="mu-blog-meta">
        <li>by: <%= context.user.email %> </li>
        <li><%= link_to context.category.name, category_path(context.category_id) if context.category%></li>
        <li><i class="fa fa-heart-o"></i><%= context.favourites.count %></li>
      </ul>
      <ul><small class="text-muted"><%= context.created_at%></small></ul>
      <h2 class="mu-blog-item-title"><a href="<%=context_path(context)%>"><%= context.title %></a></h2>
      <p><%= truncate(context.description,length: 50, separator: ' ') %></p>
      <a class="mu-blg-readmore-btn" href="<%=context_path(context)%>">Read more <i class="fa fa-long-arrow-right"></i></a>
    </div>
  </article>
</div>

app/views/contexts/_form.html.erb
<%= form_with model: @context, local: true do |form|%>

  <% if @context.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@context.errors.count, "error") %> prohibited
        this context from being saved:
      </h2>
      <ul>
        <% @context.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>


    <div class="form-group" >
      <%= form.label :title %><br>
      <%= form.text_field :title, class: "form-control rounded-0" %>
    </div>

    <div class="form-group shadow-textarea">
      <%= form.label :description %><br>
      <%= form.text_area :description, class: "form-control z-depth-1", rows: 7 %>
    </div>

    <p>
      <%= form.select :category_id, options_for_select(@categories.map{|c| [ c.name, c.id ] }), {:prompt => 'Select one category'}, {class: "btn btn-outline-primary btn-sm"}%>
    </p>

    <p>
      <%= form.submit @submit, :class => "btn btn-outline-primary btn-sm" %>
    </p>
<% end %>

app/views/contexts/edit.html.erb
<div class="container">
  <div class='row'>
    <div class="col-sm-12">
      <div class="mt-4 mb-4">
        <%= link_to 'Back', contexts_path, class: "btn btn-outline-primary btn-sm"%>
        <h1>Edit context</h1>
      </div>
    </div>
  </div>
</div>
<div class="container">
  <div class='row'>
    <div class="col-sm-12">
      <%= render 'form' %>
    </div>
  </div>
</div>

app/views/contexts/index.html.erb
<!-- Start Portfolio -->
<section id="mu-portfolio">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <div class="mu-portfolio-area">
          <!-- Title -->
          <div class="row">
            <div class="col-md-12">
              <div class="mu-title">
                <h2>Contexts</h2>
                <% if current_user%>
                  <%= link_to 'Add context', new_context_path(@context), class: "btn btn-outline-secondary btn-sm mb-3" %>
                <% end %>
              </div>
            </div>
          </div>

          <div class="row">
              <!-- Start Portfolio Filter -->
              <div class="mu-portfolio-filter-area">
                <ul class="mu-simplefilter">
                  <li class="active" data-filter="all" href="/contexts">All</li>
                  <% @categories.each do |category|%>
                  <li data-filter="1"><span>/</span><%= link_to category.name, category_path(category) %></li>
                  <%end%>
                </ul>
              </div>

              <!-- Start Portfolio Content -->
              <div class="mu-portfolio-content">
                <div class="row">
                  <% @contexts.each do |context| %>
                    <%= render 'context_card', context: context  %>
                  <% end %>
                </div>
              </div>
          </div>
        </div>
      </div>
    </div>
</section>

app/views/contexts/new.html.erb
<div class="container">
  <div class='row'>
    <div class="col-sm-12">
      <div class="mt-4 mb-4">
        <%= link_to 'Back', contexts_path, class: "btn btn-outline-primary btn-sm"%>
        <h1>New Context</h1>
      </div>
    </div>
  </div>
</div>
<div class="container">
  <div class='row'>
    <div class="col-sm-12">
      <%= render 'form' %>
    </div>
  </div>
</div>

app/views/contexts/show.html.erb
<div class="container py-3">
  <div class="row justify-content-around">

    <div class="col-sm-6 col-md-4">
      <div class="row">
        <%= load_image_for(@context) %>  
      </div>
    </div>

    <div class="col-sm-6 col-md-8">
      <div class="row text-left">
        <div class="col-12">
          <h2><%= @context.title %></h2>
          <p>by: <%= @context.user.email %></p>
        </div>
        <div class="col-12 mb-3">
          <%= @context.description %>
        </div>
      </div>
      <div class="row text-left">
        <div class="col-12 py-2">
          <% if current_user && @context.user_id == current_user.id %>
            <%= link_to 'Edit', edit_context_path(@context), class: "btn btn-outline-primary btn-sm mb-3" %>
          <% end %>
          <% if current_user%>
          <span id="context-<%= @context.id %>">
            <%= link_to_toggle_context_favourite @context, current_user %>
          </span>
          <% end %>
        </div>
      </div>
    </div>

  </div>
</div>

<!-- Start related post -->
<div class="container">
  <div class="row py-5">
    <div class="col-sm-12">
      <div class="mu-related-post">
        <h2 class="mu-related-post-title ">You must read</h2>
        <div class="row">
          <div class="col">
            <%= render 'shared/accordian'%>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>