config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
  devise_for :users
  resources :categories
  resources :contexts do
    resources :information_posts
    resources :pictures
    resource :favourite, only: %w(update destroy), module: 'contexts'
    resource :redaction, only: %w(edit), module: 'contexts', controller: 'redaction'
    collection do
      get 'redaction', controller: 'contexts/redaction', action: 'index'
    end
  end
  resources :webscraping, only: %w(index), module: 'contexts'
  root 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :contexts
  validates :name, presence: true
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController


  def index
    @categories = Category.all
  end

  def show
    @category = Category.find(params[:id])
  end

  def new
    @category = Category.new
    @submit = 'New category'
  end

  def edit
    @category = Category.find(params[:id])
  end


  def create
    @category = Category.new(category_params)

    if @category && @category.save
      redirect_to @category, notice: 'Category saved!'
    else
      render 'new'
    end
  end

  def update
    @category = Category.find(params[:id])

    if @category.update(category_params)
      redirect_to @category
    else
      render 'edit'
    end
    @submit = 'Update category'
  end

  def destroy
    @category = Category.find(params[:id])
    @category.destroy
     redirect_to categories_path
  end




  private

  def category_params
    params.require(:category).permit(:name, :description)
  end

end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.erb
<%= form_with model: @category, local: true do |form| %>
  <% if @category.errors.any? %>
   <div id="error_explanation">
     <h2>
       <%= pluralize(@category.errors.count, "error") %> prohibited
       this category from being saved:
     </h2>
     <ul>
       <% @category.errors.full_messages.each do |msg| %>
         <li><%= msg %></li>
       <% end %>
     </ul>
   </div>
  <% end %>

  <div class="form-group" >
      <%= form.label :name %><br>
      <%= form.text_field :name, class: "form-control rounded-0" %>
  </div>

  <div class="form-group shadow-textarea">
      <%= form.label :description %><br>
      <%= form.text_area :description, class: "form-control z-depth-1", rows: 7 %>
  </div>

  <p>
      <%= form.submit @submit, :class => "btn btn-outline-primary btn-sm" %>
  </p>
<% end %>

app/views/categories/edit.html.erb
<div class="container">
  <div class='row'>
    <div class="col-sm-12">
      <div class="mt-4 mb-4">
        <h1>Edit Category</h1>
      </div>
    </div>
  </div>
</div>
<div class="container">
  <div class='row'>
    <div class="col-sm-12">
      <%= render 'form' %>
    </div>
  </div>
</div>

app/views/categories/index.html.erb
<div class="container">
  <div class='row'>
    <div class="col-sm-12">
      <div class="mt-4 mb-4">
        <h1>Listing categories <%= link_to 'New category', new_category_path, class: "btn btn-outline-primary btn-sm" %></h1>
      </div>
    </div>
  </div>


  <div class="row" >
    <div class="col-sm-12">
      <% @categories.each do |category| %>
        <div class="card mb-4">
        <h5 class="card-header"><%= category.name %></h5>
          <div class="card-body">
            <%= link_to 'Show', category_path(category),class: "btn btn-outline-primary btn-sm" %>
            <%= link_to 'Edit', edit_category_path(category), class: "btn btn-outline-primary btn-sm" %>
            <%= link_to 'Destroy', category_path(category), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-outline-danger btn-sm" %>
          </div>
        </div>
      <% end %>
    </div>
  </div>



</div>

app/views/categories/new.html.erb
<div class="container">
  <div class='row'>
    <div class="col-sm-12">
      <div class="mt-4 mb-4">
        <h1>New Category</h1>
      </div>
    </div>
  </div>
</div>
<div class="container">
  <div class='row'>
    <div class="col-sm-12">
      <%= render 'form' %>
    </div>
  </div>
</div>

app/views/categories/show.html.erb
<div class="container mt-4 mb-4 bg-light" >
  <div class="row justify-content-between">
    <div class="col-sm-6 col-md-12">
      <h1><%= @category.name %></h1>
      <%= link_to 'Edit', edit_category_path(@category), class: "btn btn-outline-primary btn-sm mb-3" %>
    </div>
  </div>
</div>

<div class="container mt-4 mb-4" >
  <div class="row">
    <div class="col-md-12">
      <h3> Contexts under this category </h3>
        <div class="card-deck">
          <% if @category.contexts.published.empty? %>
            <p> There are no contexts under this category</p>
          <% else %>
            <% @category.contexts.published.each do |context| %>
              <%= render 'contexts/context_card', context: context  %>
            <%end%>
          <% end %>
      </div>
    </div>
  </div>
</div>